In [13]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense,Input
from tensorflow.keras.models import Sequential
from tensorflow.keras.activations import sigmoid
from lab_coffee_utils import load_coffee_data

In [14]:
x,y=load_coffee_data()
print(x.shape,y.shape)

(200, 2) (200, 1)


In [21]:
print(np.max(x[:,0]),np.min(x[:,0]))
print(np.max(x[:,1]),np.min(x[:,1]))
norm_l=tf.keras.layers.Normalization(axis=-1)
norm_l.adapt(x)
xn=norm_l(x)
print(np.max(xn[:,0]),np.min(xn[:,0]))
print(np.max(xn[:,1]),np.min(xn[:,1]))


284.99434167453603 151.32372212128612
15.454206928801511 11.512747082472469
1.6597542 -1.6852185
1.7932389 -1.6996713


In [23]:
Xt = np.tile(xn,(1000,1))
Yt= np.tile(y,(1000,1))   
print(Xt.shape, Yt.shape)   

(200000, 2) (200000, 1)


In [25]:
tf.random.set_seed(1234)
model=Sequential([
    tf.keras.Input(shape=(2,)),
    Dense(units=3,activation='sigmoid',name='layer1'),
    Dense(units=1,activation='sigmoid',name='layer2')
])

In [26]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ layer1 (Dense)                  │ (None, 3)              │             9 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer2 (Dense)                  │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13 (52.00 B)

 Trainable params: 13 (52.00 B)

 Non-trainable params: 0 (0.00 B)

In [27]:
L1_num_params = 2 * 3 + 3   # W1 parameters  + b1 parameters
L2_num_params = 3 * 1 + 1   # W2 parameters  + b2 parameters
print("L1 params = ", L1_num_params, ", L2 params = ", L2_num_params  )

L1 params =  9 , L2 params =  4


In [29]:
w1,b1=model.get_layer('layer1').get_weights()
w2,b2=model.get_layer('layer2').get_weights()
print(f"W1{w1.shape}:\n", w1, f"\nb1{b1.shape}:", b1)
print(f"W2{w2.shape}:\n", w2, f"\nb2{b2.shape}:", b2)

W1(2, 3):
 [[-1.01 -0.62 -0.09]
 [-0.41  1.08 -0.1 ]] 
b1(3,): [0. 0. 0.]
W2(3, 1):
 [[ 0.47]
 [-0.87]
 [-0.95]] 
b2(1,): [0.]


In [31]:
model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.01)
)

model.fit(
    Xt,Yt,
    epochs=10,
)

Epoch 1/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 4s 613us/step - loss: 0.2543
Epoch 2/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 4s 608us/step - loss: 0.1034
Epoch 3/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 4s 616us/step - loss: 0.0255
Epoch 4/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 4s 613us/step - loss: 0.0140
Epoch 5/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 4s 610us/step - loss: 0.0092
Epoch 6/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 4s 634us/step - loss: 0.0064
Epoch 7/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 4s 670us/step - loss: 0.0044
Epoch 8/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 4s 653us/step - loss: 0.0031
Epoch 9/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 4s 639us/step - loss: 0.0022
Epoch 10/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 4s 632us/step - loss: 0.0015


In [32]:
w1,b1=model.get_layer('layer1').get_weights()
w2,b2=model.get_layer('layer2').get_weights()
print("W1:\n", w1, "\nb1:", b1)
print("W2:\n", w2, "\nb2:", b2)

W1:
 [[  0.17  14.56 -10.99]
 [ 10.57  12.15  -0.26]] 
b1: [ 12.71   2.02 -11.85]
W2:
 [[ 46.24]
 [-48.31]
 [-56.25]] 
b2: [-14.39]


In [33]:
# After finishing the lab later, you can re-run all 
# cells except this one to see if your trained model
# gets the same results.

# Set weights from a previous run. 
W1 = np.array([
    [-8.94,  0.29, 12.89],
    [-0.17, -7.34, 10.79]] )
b1 = np.array([-9.87, -9.28,  1.01])
W2 = np.array([
    [-31.38],
    [-27.86],
    [-32.79]])
b2 = np.array([15.54])

# Replace the weights from your trained model with
# the values above.
model.get_layer("layer1").set_weights([W1,b1])
model.get_layer("layer2").set_weights([W2,b2])

In [34]:
# Check if the weights are successfully replaced
W1, b1 = model.get_layer("layer1").get_weights()
W2, b2 = model.get_layer("layer2").get_weights()
print("W1:\n", W1, "\nb1:", b1)
print("W2:\n", W2, "\nb2:", b2)

W1:
 [[-8.94  0.29 12.89]
 [-0.17 -7.34 10.79]] 
b1: [-9.87 -9.28  1.01]
W2:
 [[-31.38]
 [-27.86]
 [-32.79]] 
b2: [15.54]


In [35]:
x_test=np.array([[200,13.9],
[200,17]])
x_testn=norm_l(x_test)
predictions=model.predict(x_testn)
print('Predictions=\n',predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step
Predictions=
 [[9.63e-01]
 [3.03e-08]]


In [36]:
yhat = np.zeros_like(predictions)
for i in range(len(predictions)):
    if predictions[i] >= 0.5:
        yhat[i] = 1
    else:
        yhat[i] = 0
print(f"decisions = \n{yhat}")

decisions = 
[[1.]
 [0.]]


In [37]:
yhat = (predictions >= 0.5).astype(int)
print(f"decisions = \n{yhat}")

decisions = 
[[1]
 [0]]
